# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [3]:
a = np.arange(10,50)

4. Find the shape of previous array in question 3

In [4]:
a.shape

(40,)

5. Print the type of the previous array in question 3

In [5]:
a.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [6]:
np.__version__

'1.19.5'

In [7]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


7. Print the dimension of the array in question 3


In [8]:
a.ndim

1

8. Create a boolean array with all the True values

In [9]:
np.ones(5, dtype=bool)

array([ True,  True,  True,  True,  True])

9. Create a two dimensional array




In [10]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
arr.ndim

[[1 2 3]
 [4 5 6]]


2

10. Create a three dimensional array



In [11]:
arr = np.array([[[1,2,3],[4,5,6]]])
arr.ndim

3

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [12]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [13]:
b = np.zeros(10)
b[5] = 1
b

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [15]:
arr = np.array([1, 2, 3, 4, 5],dtype = float)
arr.dtype

dtype('float64')

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [16]:
arr1 = np.array([[1., 2., 3.],
                 [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],
                 [7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [17]:
arr1 = np.array([[1., 2., 3.],
                 [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],
                 [7., 2., 12.]])

arr1 == arr2

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [18]:
a = np.arange(0,10)
a[a%2==1]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [19]:
a = np.arange(0,10)
a[a%2==1] = -1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [20]:
arr = np.arange(10)
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [21]:
arr = np.ones((4,4))
arr[1:-1,1:-1] = 0
arr

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [22]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

arr2d[1,1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [23]:
arr3d = np.array([[[1, 2, 3],
                   [4, 5, 6]],
                  
                  [[7, 8, 9],
                   [10, 11, 12]]])
arr3d[:,0,:]=64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[64, 64, 64],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [24]:
a = np.arange(10).reshape(2,5)
print(a[0,:])

[0 1 2 3 4]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [25]:
a = np.arange(10).reshape(2,5)
a[1,1,]

6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [26]:
a = np.arange(10).reshape(2,5)
print(a)
a[:2,2:3]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[2],
       [7]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [27]:
arr = np.random.randn(10,10)
print(arr.min())
print(arr.max())

-2.3900438105650186
2.1034663259370703


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [29]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.searchsorted(a, np.intersect1d(a, b))

array([1, 5], dtype=int64)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [30]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names != 'Will']

array([[ 0.22055467,  0.63005072,  1.60642863,  0.26603908],
       [ 0.23489952,  0.28002773,  1.32892143,  0.63589341],
       [ 0.25334178, -0.83319039,  2.14514946,  1.36686829],
       [ 0.18790504,  0.20075928, -0.40633695, -1.15026745],
       [ 0.99991416, -1.73232684, -1.30324825, -0.16465595]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [31]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
arr = data[names!='will']
arr1 = data[names!='Joe']
arr1

array([[-0.95108658, -2.17977809, -0.61714021,  1.60229047],
       [ 0.03033891, -0.72119282,  1.06712394,  0.99582345],
       [ 0.20492837, -0.89192739, -0.09443353,  0.41037032],
       [-0.1445734 ,  0.88545005,  0.78956952, -0.86281223]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [32]:
np.arange(1,16 , dtype=float ).reshape(5,3)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [33]:
arr = np.arange(1,17, dtype = float).reshape(2,2,4)
arr

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]])

33. Swap axes of the array you created in Question 32

In [34]:
print(arr.reshape(2,4,2))
print('\n2nd ans:')
print(arr.swapaxes(2,1))

[[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]
  [13. 14.]
  [15. 16.]]]

2nd ans:
[[[ 1.  5.]
  [ 2.  6.]
  [ 3.  7.]
  [ 4.  8.]]

 [[ 9. 13.]
  [10. 14.]
  [11. 15.]
  [12. 16.]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [35]:
a = np.arange(10)
b = np.sqrt(a)
print(b)
np.where(b < 0.5, 0, b )

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [36]:
a = np.random.randn(12)
b = np.random.randn(12)
np.array([max(a),max(b)])

array([1.67676319, 1.82191956])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [37]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [38]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

dum = []
for i in a:
    if i not in b:
        dum.append(i)
output = np.array(dum)
print(output)
type(output)

[1 2 3 4]


numpy.ndarray

In [39]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

comn_val = set(a) & set(b)

a = a.tolist()
b = b.tolist()

for value in comn_val:
    a.remove(value)
    b.remove(value)

a = np.array(a)
b = np.array(b)
a

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [40]:
arr = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
print(arr)
b = np.delete(arr,1,axis = 1)
np.insert(b,1,10,axis = 1)

[[34 43 73]
 [82 22 12]
 [53 94 66]]


array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [41]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [42]:
np.random.randn(20).cumsum()

array([ -0.70442554,  -1.54565925,  -2.44839229,  -3.82386356,
        -4.02635825,  -3.00955715,  -0.88614913,  -2.81097692,
        -3.17106724,  -2.51229297,  -2.70166673,  -2.33508375,
        -4.55513971,  -5.81268884,  -6.90107782,  -7.85762416,
        -9.04941258, -10.62197759, -10.17111763,  -9.92625698])